### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by amahrt** [elastic/app-search-node#13]
It would be great to have out of the box typescript support for this and other libraries.

**Comment by yakhinvadim** [comment]
Hey Alexander, thanks for opening an issue. We see that there's a growing demand for TS support, so we'll consider adding it to our libraries.

**Comment by preetjdp** [comment]
Hi are there any plans to include this in the near future.

**Comment by JasonStoltz** [comment]
None currently.

**Comment by dsmith3197** [comment]
Hey, it would be really great if you guys added typescript definitions to your projects.  I think there is a real demand for it.

**Comment by nshapkar** [comment]
Any update on this?

**Comment by JasonStoltz** [comment]
No update, sorry. The work is not planned either 😢

**Comment by richbai90** [comment]
These aren't the best typings, but they should provide some basic TS support.

https://gist.github.com/richbai90/8fc56cb3d9b71d0beb46dc34a982f7af

**Comment by davidq2q** [comment]
It seems like appsearch is the worst maintained and documented product in the elastic stack. It truly baffles me considering that elastic search is such a wonderful piece of engineering.

**Comment by JasonStoltz** [comment]
Hey @davidq2q, I'm sorry to hear you feel that way. These clients are unfortunately hard for us to keep up with. We've been spending most of our effort on the core product itself.

**Comment by izakfilmalter** [comment]
It's just an acceptable from my pov. I am comparing App Search vs Algolia vs TypeSense for my firebase app. I want to use elastic because I have used it before on other projects and it's been great. It feels like all the effort for App Search has gone into a nice management UI, don't get me wrong I like a nice UI, but the client libraries and lack of components you can use out of the box is a big miss. So I keep trundling along, trying to use App Search, oh look no typescript support. Issue opened literally almost 2 years ago. 

A product with a nice UI and horrible dev tooling is not a product when people actually have to implement it in their code bases. At least start with doing what TypeSense does and make a wrapper for instantsearch.js while you work on making something better. 

I can't use this product if I can't implement it in a way that satisfies my constraints, type safety is a massively important constraint in 2021. This feels like Mongo Realm tbh. Awesome marketing site, slick management UI, docs that suck, and clients that are even worse.

**Comment by serenachou** [comment]
@izakfilmalter  Hi there! I'm a product manager on the Enterprise Search team, and this feedback is important. You as a developer are who we want to make things easiest for! There's a lot to unpack here in your response, would you be willing to jump on a zoom call with me to talk a bit more in depth about your experiences so far? I'd love to take your feedback to sanity check what we have on the roadmap. If that works for you, let me know and I can send you a calendly link to schedule a session or you can let me know a convenient time that suits.

**Comment by JasonStoltz** [comment]
@izakfilmalter I appreciate that feedback. You are absolutely right, we need to improve in this area.

**Comment by JasonStoltz** [comment]
I published some types if anyone wants to take a look and do some testing: https://github.com/elastic/app-search-node/pull/50.

```
npm install --save elastic/app-search-node@7.15.2-beta.0
```

Wish I could have provided these for ya'll years ago 😅 . Sorry for the delay.

**Comment by lcwill** [comment]
Hi @JasonStoltz, thanks for working on this! Any update on getting #50 merged?

**Comment by JasonStoltz** [comment]
Alright, sorry for the delay. We've been holding out on this waiting for https://www.npmjs.com/package/@elastic/enterprise-search, which supersedes this client.

**Comment by izakfilmalter** [comment]
This is classic Elastic Search at their finest. We're gonna fix the problem by making a whole new lib with zero documentation. Give me a break.

**Comment by JasonStoltz** [comment]
Hey @izakfilmalter. Sorry about that. I certainly meant no harm here. I simply assumed that adding TS support to a deprecated client would not be valuable. I am happy to re-open and merge that PR if you'd find it valuable.

**Comment by JasonStoltz** [comment]
I don't believe the docs are quite ready yet, but they can be found:

There are docs for the Universal client here: https://github.com/elastic/enterprise-search-js/tree/main/packages/enterprise-search-universal

And limited docs for the Node client here: https://github.com/elastic/enterprise-search-js/tree/main/packages/enterprise-search

Documentation for the individual endpoints can be found here: https://github.com/elastic/enterprise-search-js/tree/main/packages/enterprise-search
